version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: sca-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: source_agent
      MYSQL_USER: dump
      MYSQL_PASSWORD: dump111
    ports:
      - "6006:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./script/init-sql.sql:/docker-entrypoint-initdb.d/init-sql.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: sca-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: sca-frontend
    ports:
      - "5173:80"

volumes:
  db_data:

